define(function(require, exports, module) {	
	var base = module.uri.replace(/js[\/\\]style\-switch\.js.*?$/,"");

	var style = {
	    '默认':{
	        head_bg : 	base+"/images/head_bg.png",
	        head_icon: 	base+"/images/head_icon.png",
	        head_logo: 	base+"/images/headnav_bg.png",
	        tree_nav_bg:"#dbede9",
	        tree_nav_hover:"#8ddacb",
	        tree_container:"#2cac93",
	        tree_select:"#188b75",
	        loading_image: 	base+"/images/loading.gif",
	        list_move_color:"#33c2a6",
	        style_lighter:"#5ed0ba",
	        style_normal:"#2cac93",
	        form_icons: 	base+"/images/form.png",
	        nameColor: "#2cac93",
	        treelink: base + "/images/tree-icons.png",
	        treeNav: "#dbede9",
	        treeSelect: "#8ddacb"
	    },
        /*
		'd60':{
			head_bg: 	base+"/images/head_bg-d60.png",
			head_icon: 	base+"/images/head_icon.png",
			head_logo: 	base+"/images/t.png",
			tree_nav_bg:"#fffeee",
			tree_nav_hover:"#fa8011",
			tree_container:"#dd6600",
			tree_select:"#d40",
			loading_image: 	base+"/images/loading.gif",
			list_move_color:"#f07206",
			style_lighter:"#fa8011",
			style_normal:"#dd6600",
			form_icons: 	base+"/images/form.png",
			nameColor:"#dd6600"
		},
		'f00':{
			head_bg: 	base+"/images/head_bg-d60.png",
			head_icon: 	base+"/images/head_icon.png",
			head_logo: 	base+"/images/t.png",
			tree_nav_bg:"#fffeee",
			tree_nav_hover:"#fa8011",
			tree_container:"#f00",
			tree_select:"#f00",
			loading_image: 	base+"/images/loading.gif",
			list_move_color:"#f00",
			style_lighter:"#f00",
			style_normal:"#f00",
			form_icons: 	base+"/images/form.png",
			nameColor:"#f00"
		},
        */
		'薄红梅': {
		    head_bg: base + "/images/bohongmei/head_bg.png",
		    head_icon: base + "/images/bohongmei/head_icon.png",
		    head_logo: base + "/images/bohongmei/headnav_bg.png",
		    tree_nav_bg: "#e99fb7",
		    tree_nav_hover: "#c95e81",
		    tree_container: "#c95e81",
		    tree_select: "#c95e81",
		    loading_image: base + "/images/loading.gif",
		    list_move_color: "#dd88a4",
		    style_lighter: "#e99fb7",
		    style_normal: "#c95e81",
		    form_icons: base + "/images/bohongmei/form.png",
		    nameColor: "#2cac93",
		    treelink: base + "/images/bohongmei/tree-icons.png",
		    treeNav: "#e99fb7",
		    treeSelect: "#c95e81"
		},
		'紺蓝': {
		    head_bg: base + "/images/ganlan/head_bg.png",
		    head_icon: base + "/images/ganlan/head_icon.png",
		    head_logo: base + "/images/ganlan/headnav_bg.png",
		    tree_nav_bg: "#646bbf",
		    tree_nav_hover: "#494e8f",
		    tree_container: "#494e8f",
		    tree_select: "#646bbf",
		    loading_image: base + "/images/loading.gif",
		    list_move_color: "#7d84da",
		    style_lighter: "#494e8f",
		    style_normal: "#646bbf",
		    form_icons: base + "/images/ganlan/form.png",
		    nameColor: "#2cac93",
		    treelink: base + "/images/ganlan/tree-icons.png",
		    treeNav: "#646bbf",
		    treeSelect: "#494e8f"
		},
		'鸠羽色': {
		    head_bg: base + "/images/jiuyuse/head_bg.png",
		    head_icon: base + "/images/jiuyuse/head_icon.png",
		    head_logo: base + "/images/jiuyuse/headnav_bg.png",
		    tree_nav_bg: "#867892",
		    tree_nav_hover: "#6c6176",
		    tree_container: "#6c6176",
		    tree_select: "#6c6176",
		    loading_image: base + "/images/loading.gif",
		    list_move_color: "#9281a1",
		    style_lighter: "#867892",
		    style_normal: "#6c6176",
		    form_icons: base + "/images/jiuyuse/form.png",
		    nameColor: "#2cac93",
		    treelink: base + "/images/jiuyuse/tree-icons.png",
		    treeNav: "#867892",
		    treeSelect: "#6c6176"
		},
		'露草色': {
		    head_bg: base + "/images/loucaose/head_bg.png",
		    head_icon: base + "/images/loucaose/head_icon.png",
		    head_logo: base + "/images/loucaose/headnav_bg.png",
		    tree_nav_bg: "#59caec",
		    tree_nav_hover: "#008eb9",
		    tree_container: "#008eb9",
		    tree_select: "#008eb9",
		    loading_image: base + "/images/loading.gif",
		    list_move_color: "#2cb0d8",
		    style_lighter: "#59caec",
		    style_normal: "#008eb9",
		    form_icons: base + "/images/loucaose/form.png",
		    nameColor: "#2cac93",
		    treelink: base + "/images/loucaose/tree-icons.png",
		    treeNav: "#59caec",
		    treeSelect: "#008eb9"
		},
		'煤竹色': {
		    head_bg: base + "/images/meizhuse/head_bg.png",
		    head_icon: base + "/images/meizhuse/head_icon.png",
		    head_logo: base + "/images/meizhuse/headnav_bg.png",
		    tree_nav_bg: "#bb9490",
		    tree_nav_hover: "#6c4c49",
		    tree_container: "#6c4c49",
		    tree_select: "#bb9490",
		    loading_image: base + "/images/loading.gif",
		    list_move_color: "#8b6460",
		    style_lighter: "#6c4c49",
		    style_normal: "#bb9490",
		    form_icons: base + "/images/meizhuse/form.png",
		    nameColor: "#2cac93",
		    treelink: base + "/images/meizhuse/tree-icons.png",
		    treeNav: "#bb9490",
		    treeSelect: "#6c4c49"
		},
		'媚茶': {
		    head_bg: base + "/images/meicha/head_bg.png",
		    head_icon: base + "/images/meicha/head_icon.png",
		    head_logo: base + "/images/meicha/headnav_bg.png",
		    tree_nav_bg: "#808745",
		    tree_nav_hover: "#454926",
		    tree_container: "#454926",
		    tree_select: "#808745",
		    loading_image: base + "/images/loading.gif",
		    list_move_color: "#939772",
		    style_lighter: "#454926",
		    style_normal: "#808745",
		    form_icons: base + "/images/meicha/form.png",
		    nameColor: "#2cac93",
		    treelink: base + "/images/meicha/tree-icons.png",
		    treeNav: "#808745",
		    treeSelect: "#454926"
		},
		'浓鼠': {
		    head_bg: base + "/images/nongshu/head_bg.png",
		    head_icon: base + "/images/nongshu/head_icon.png",
		    head_logo: base + "/images/nongshu/headnav_bg.png",
		    tree_nav_bg: "#b5a9c8",
		    tree_nav_hover: "#3c3645",
		    tree_container: "#3c3645",
		    tree_select: "#b5a9c8",
		    loading_image: base + "/images/loading.gif",
		    list_move_color: "#6b578c",
		    style_lighter: "#3c3645",
		    style_normal: "#b5a9c8",
		    form_icons: base + "/images/nongshu/form.png",
		    nameColor: "#2cac93",
		    treelink: base + "/images/nongshu/tree-icons.png",
		    treeNav: "#b5a9c8",
		    treeSelect: "#3c3645"
		},
		'铅丹红': {
		    head_bg: base + "/images/qiandanhong/head_bg.png",
		    head_icon: base + "/images/qiandanhong/head_icon.png",
		    head_logo: base + "/images/qiandanhong/headnav_bg.png",
		    tree_nav_bg: "#f8967b",
		    tree_nav_hover: "#c75d41",
		    tree_container: "#c75d41",
		    tree_select: "#c75d41",
		    loading_image: base + "/images/loading.gif",
		    list_move_color: "#a94326",
		    style_lighter: "#f8967b",
		    style_normal: "#c75d41",
		    form_icons: base + "/images/qiandanhong/form.png",
		    nameColor: "#2cac93",
		    treelink: base + "/images/qiandanhong/tree-icons.png",
		    treeNav: "#f8967b",
		    treeSelect: "#c75d41"
		},
		'生壁色': {
		    head_bg: base + "/images/shengbise/head_bg.png",
		    head_icon: base + "/images/shengbise/head_icon.png",
		    head_logo: base + "/images/shengbise/headnav_bg.png",
		    tree_nav_bg: "#838061",
		    tree_nav_hover: "#5f5d46",
		    tree_container: "#5f5d46",
		    tree_select: "#838061",
		    loading_image: base + "/images/loading.gif",
		    list_move_color: "#48430d",
		    style_lighter: "#5f5d46",
		    style_normal: "#838061",
		    form_icons: base + "/images/shengbise/form.png",
		    nameColor: "#2cac93",
		    treelink: base + "/images/shengbise/tree-icons.png",
		    treeNav: "#838061",
		    treeSelect: "#5f5d46"
		},
		'熟褐': {
		    head_bg: base + "/images/shuhe/head_bg.png",
		    head_icon: base + "/images/shuhe/head_icon.png",
		    head_logo: base + "/images/shuhe/headnav_bg.png",
		    tree_nav_bg: "#dd823d",
		    tree_nav_hover: "#843900",
		    tree_container: "#843900",
		    tree_select: "#dd823d",
		    loading_image: base + "/images/loading.gif",
		    list_move_color: "#a94d07",
		    style_lighter: "#843900",
		    style_normal: "#dd823d",
		    form_icons: base + "/images/shuhe/form.png",
		    nameColor: "#2cac93",
		    treelink: base + "/images/shuhe/tree-icons.png",
		    treeNav: "#dd823d",
		    treeSelect: "#843900"
		},
		'藤紫': {
		    head_bg: base + "/images/tengzi/head_bg.png",
		    head_icon: base + "/images/tengzi/head_icon.png",
		    head_logo: base + "/images/tengzi/headnav_bg.png",
		    tree_nav_bg: "#a2aee8",
		    tree_nav_hover: "#6579d9",
		    tree_container: "#6579d9",
		    tree_select: "#6579d9",
		    loading_image: base + "/images/loading.gif",
		    list_move_color: "#2a45c9",
		    style_lighter: "#a2aee8",
		    style_normal: "#6579d9",
		    form_icons: base + "/images/tengzi/form.png",
		    nameColor: "#2cac93",
		    treelink: base + "/images/tengzi/tree-icons.png",
		    treeNav: "#a2aee8",
		    treeSelect: "#6579d9"
		},
		'勿忘草色': {
		    head_bg: base + "/images/wuwangcaose/head_bg.png",
		    head_icon: base + "/images/wuwangcaose/head_icon.png",
		    head_logo: base + "/images/wuwangcaose/headnav_bg.png",
		    tree_nav_bg: "#8ec9fb",
		    tree_nav_hover: "#278add",
		    tree_container: "#278add",
		    tree_select: "#278add",
		    loading_image: base + "/images/loading.gif",
		    list_move_color: "#2f7bbc",
		    style_lighter: "#8ec9fb",
		    style_normal: "#278add",
		    form_icons: base + "/images/wuwangcaose/form.png",
		    nameColor: "#2cac93",
		    treelink: base + "/images/wuwangcaose/tree-icons.png",
		    treeNav: "#8ec9fb",
		    treeSelect: "#278add"
		}
        /*
	   'bohongmei': {
		    head_bg: base + "/images/bohongmei/head_bg.png",
		    head_icon: base + "/images/bohongmei/head_icon.png",
		    head_logo: base + "/images/bohongmei/headnav_bg.png",
		    tree_nav_bg: "red",
		    tree_nav_hover: "green",
		    tree_container: "blue",
		    tree_select: "black",
		    loading_image: base + "/images/loading.gif",
		    list_move_color: "orange",
		    style_lighter: "white",
		    style_normal: "pink",
		    form_icons: base + "/images/bohongmei/form.png",
		    nameColor: "#2cac93"
	    }
        */
	};

	return style;
});